services:
  setup:
    image: alpine:3.19
    container_name: collaborative-task-management-setup
    volumes:
      - ./scripts:/scripts:ro
      - ./apps:/apps
    command: sh /scripts/setup.sh
    networks:
      - collaborative-task-management-network

  postgres:
    image: postgres:17.5-alpine
    container_name: collaborative-task-management-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collaborative_task_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      setup:
        condition: service_completed_successfully
    networks:
      - collaborative-task-management-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: collaborative-task-management-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      setup:
        condition: service_completed_successfully
    networks:
      - collaborative-task-management-network

  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
      target: development
    container_name: collaborative-task-management-auth-service
    restart: unless-stopped
    command: pnpm dev
    ports:
      - "3002:3002"
    env_file:
      - ./apps/auth-service/.env
    volumes:
      - ./apps/auth-service:/app/apps/auth-service
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/auth-service/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - collaborative-task-management-network

  tasks-service:
    build:
      context: .
      dockerfile: apps/tasks-service/Dockerfile
      target: development
    container_name: collaborative-task-management-tasks-service
    restart: unless-stopped
    command: pnpm dev
    ports:
      - "3003:3003"
    env_file:
      - ./apps/tasks-service/.env
    volumes:
      - ./apps/tasks-service:/app/apps/tasks-service
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/tasks-service/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - collaborative-task-management-network

  notifications-service:
    build:
      context: .
      dockerfile: apps/notifications-service/Dockerfile
      target: development
    container_name: collaborative-task-management-notifications-service
    restart: unless-stopped
    command: pnpm dev
    ports:
      - "3004:3004"
    env_file:
      - ./apps/notifications-service/.env
    volumes:
      - ./apps/notifications-service:/app/apps/notifications-service
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/notifications-service/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - collaborative-task-management-network

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      target: development
    container_name: collaborative-task-management-api-gateway
    restart: unless-stopped
    command: pnpm dev
    ports:
      - "3001:3001"
    env_file:
      - ./apps/api-gateway/.env
    volumes:
      - ./apps/api-gateway:/app/apps/api-gateway
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/api-gateway/node_modules
    depends_on:
      auth-service:
        condition: service_healthy
      tasks-service:
        condition: service_healthy
      notifications-service:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - collaborative-task-management-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: development
    container_name: collaborative-task-management-web
    restart: unless-stopped
    command: pnpm dev
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/web/node_modules
    depends_on:
      api-gateway:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
    networks:
      - collaborative-task-management-network

volumes:
  postgres_data:
    name: collaborative-task-management-postgres-data
  rabbitmq_data:
    name: collaborative-task-management-rabbitmq-data

networks:
  collaborative-task-management-network:
    name: collaborative-task-management-network
    driver: bridge
